### ISSUE TITLE
FEATURE + BUG: You should consider C# Keywords and add '@' sign before the field name as well And better to make it generate with JS!!

### ISSUE THREAD

**Issue by GameHackerPM** [Json2CSharp/Json2CSharpCodeGenerator#1]
Hello, I can see you just bought json2csharp.com as it's domain already got expired.. Anyway it's good to see another one, but the bad that that it doesn't be like the old one, but it's too bad to see it send to the server and return the class string, it should be even easier than that, you should make it be done within Javascript to remove any delays that might take (2-5s) sometimes depends on how long the data is.

Also you should consider putting '@' sign before any keyword like for example having a json with class name = event or continue (we all know that event and continue are C# Keywords, so they need to be transfered to @event and @continue), you can also add some small other stuff like putting the [JsonProperty("Name")] instead of the name itself (make it a radio button option) and should be with 2 modes: camel case and pascal case .. All of these could be awesome and powerful suggestions.

**Comment by Json2CSharp** [comment]
Hey GameHackerPM Thanks so much for the valuable feedback you provided!  Regarding sending the  json to the server there are plans to make it in javascript and/or improve the speed of execution,

You're totally right about the reserved keywords and adding settings for camel case/pascal and jsonpropety attributes, these will be included in future releases as settings, no worries!

Stay safe and healthy!

**Comment by tyeth** [comment]
Pull request #14 solves the second issue.
I wonder if using blazor could be a good middleground (the libraries are getting tree-shaking now so not soo huge)

**Comment by Json2CSharp** [comment]
Considergin this as done thanks to tyeth
