### ISSUE TITLE
[enhancement] Consider making this a visual studio extension or a global package we can run from terminal

### ISSUE THREAD

**Issue by arivera12** [Json2CSharp/Json2CSharpCodeGenerator#11]
It would be cool this available as vs extension were we can:

Rigth click the .json file and convert to c# models specifying the output folder.

Also this could be a global nuget package were we can run from terminal like:

`dotnet Json2CSharpCodeGenerator -f myfile.json -o myfile.cs`

**Comment by Json2CSharp** [comment]
Good point, currently we're trying to fix some existing bugs and enhancement, but if someone is interested in this, they can fork the code and make a nuget package with cli commands, should be easy,

will be closing this issue until someone is maybe interesetd in making as a nuget packge 
Thanks for your feedback !
