### ISSUE TITLE
JsonProperty Attribute is always Added in Pascal Case

### ISSUE THREAD

**Issue by dogac00** [Json2CSharp/Json2CSharpCodeGenerator#12]
When I paste the JSON to convert it to C#, if I click Use Pascal Case, it is always adding JsonProperty attribute on properties. I am using .NET Core's JsonSerializer. I don't want to add a new dependency to my project. Even when I unclick Add JsonProperty Attributes, it always adds them.

**Comment by dogac00** [comment]
![Json2CSharp](https://user-images.githubusercontent.com/26314896/91437484-a3c90f00-e872-11ea-938b-1e7191e9c6a8.png)

**Comment by Json2CSharp** [comment]
Hey, i think in this case i might add an option to remove the json attributes, even if the Class name doesn't match the Json property.

I will mark this as enhancement, this will be rolled in the future hopefully,
but yes you got a point, you don't always need to add .net related dependencies..

Thanks for letting me know !

**Comment by dogac00** [comment]
I opened a pull request to close this issue.

I updated the `CSharpCodeWriter` class. I made changes such that the class generated Newtonsoft using directive and AddJsonProperty codes only if `config.UseJsonAttributes` is true.

PR [link](https://github.com/Json2CSharp/Json2CSharpCodeGenerator/pull/13).

I hope this helps.

Thanks.

**Comment by Json2CSharp** [comment]
Merged this , in the site if you click on Use Pascal should automatically check json attributes, you can optionally uncheck it , Thanks for your contribution !
