### ISSUE TITLE
Bug: Json Fields containing a hypen

### ISSUE THREAD

**Issue by quotschmacher** [Json2CSharp/Json2CSharpCodeGenerator#2]
if a json field name contains a hyphen, code like this is generated:

`public List<EStatu> e-status { get; set; }`

no valid code.
what would work:

`[JsonProperty("e-status")]
public List<EStatu> e_status { get; set; }`

**Comment by Json2CSharp** [comment]
Thank you for reporting this error, this will be fixed in the next couple of days or so. Stay safe !

**Comment by Json2CSharp** [comment]
This issue is fixed, thanks for the fyi
