### ISSUE TITLE
Escaped quotation marks breaks converter

### ISSUE THREAD

**Issue by StaticBR** [Json2CSharp/Json2CSharpCodeGenerator#25]
Hi,
if the JSON uses an escaped " within an String the conversion fails.
And the server returns "Wrong JSON format"

This is a simple example that breaks the converter:
`{
  "someText": " some \"special\" Text"
}`

**Comment by Json2CSharp** [comment]
hmm it should remove the escaped double quotes but its not as easy as it seems there are a lot of cases, i'll see what i can do about this

thanks for letting me know

**Comment by Json2CSharp** [comment]
This is fixed, thanks a lot for letting me know
