### ISSUE TITLE
Class for top-level JSON Array has an root property

### ISSUE THREAD

**Issue by MarkusHorstmann** [Json2CSharp/Json2CSharpCodeGenerator#3]
[
  {
    "prop1": "value1"
  }
]

Results in:
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
    public class MyArray    {
        public string prop1 { get; set; } 
    }
    public class Root    {
        public List<MyArray> MyArray { get; set; } 
    }

Should be something like: 
   JsonConvert.DeserializeObject<List<MyArray>>(myJsonResponse);

**Comment by Json2CSharp** [comment]
Makes sense.. no need for the root object if you only have an array. 
I'll review this case and see what can i do about it.

Thanks for the valuable input 👍

**Comment by Json2CSharp** [comment]
ill close this for now as this seems like a special case for when you only have an array in place, ill reopen this if its requested again or anyone was interested in doing it
