### ISSUE TITLE
Return keyword in JAVA

### ISSUE THREAD

**Issue by giuseppe-pinto** [Json2CSharp/Json2CSharpCodeGenerator#38]
If you have a json to convert in java pojo with a field called "return", this creates a problem on the Java pojo obviously. 

This is an exmaple:

`
{
    "passengers": {
        "adults": 1
        },
    "route": {
        "outward": {
                "segments": [
                    {
                        "airline": "AN_AIRLINE",
                        "flight_number": "1234"
                    }
                ]              
            },
         "return": {
                "segments": [
                    {
                        "airline": "AN_AIRLINE",
                        "flight_number": "1234"
                    }
                ]              
            }
    }
}
`

**Comment by Json2CSharp** [comment]
Hey thanks for letting me know ! This should be an easy fix

**Comment by Json2CSharp** [comment]
This is fixed now its renaming "return" string, example

// import com.fasterxml.jackson.databind.ObjectMapper; // version 2.11.1
// import com.fasterxml.jackson.annotation.JsonProperty; // version 2.11.1
/* ObjectMapper om = new ObjectMapper();
Root root = om.readValue(myJsonString, Root.class); */
public class Outward{
    public ArrayList<Segment> segments;
}

public class Passengers{
    public int adults;
}

public class Return{
    public ArrayList<Segment> segments;
}

public class Root{
    public Passengers passengers;
    public Route route;
}

public class Route{
    public Outward outward;
    @JsonProperty("return") 
    public Return myreturn;
}

public class Segment{
    public String airline;
    public String flight_number;
}
