### ISSUE TITLE
C# Datetime Imports

### ISSUE THREAD

**Issue by luizgserpa** [Json2CSharp/Json2CSharpCodeGenerator#40]
When converting from Json to C# I realized that when same property of class use type Datetime the using statement is not implemented.

I found this on class CSharpCodeWriter.WriteFileStart

`sw.AppendLine("using System;");`

I my tests from the website It's not working.

**Comment by Json2CSharp** [comment]
Can you please provide an example of the input and the expected output ?

**Comment by luizgserpa** [comment]
Input:

`{
   "count":1,
   "id":19863,
   "System.CreatedDate":"2020-11-16T21:41:02.7Z"
}`

Expected output:

```
using System;
using System.Text.Json.Serialization; 
namespace Automation.Entities.Microsoft.WorkItemBacklogs{ 

    public class Root    {
        [JsonPropertyName("count")]
        public int Count { get; set; } 

        [JsonPropertyName("id")]
        public int Id { get; set; } 

        [JsonPropertyName("System.CreatedDate")]
        public DateTime SystemCreatedDate { get; set; } 
    }

}
```

Reveiced output:

```
using System.Text.Json.Serialization; 
namespace Automation.Entities.Microsoft.WorkItemBacklogs{ 

    public class Root    {
        [JsonPropertyName("count")]
        public int Count { get; set; } 

        [JsonPropertyName("id")]
        public int Id { get; set; } 

        [JsonPropertyName("System.CreatedDate")]
        public DateTime SystemCreatedDate { get; set; } 
    }

}
```

Configuration:

- [ ]  Use Pascal Case
- [ ]  Add JsonProperty Attributes
- [ ]  Use Fields
- [x]  Use JsonPropertyName (.NET Core)

**Comment by Json2CSharp** [comment]
Thinking of adding an "Add using statements" option which will add any necessary using statements

**Comment by luizgserpa** [comment]
It's a good idea, If I can help with something else, codinging, testing, just let me know.

Thank you for your time.

**Comment by Json2CSharp** [comment]
Oh snap now i got it, you meant when you zipped the classes as files it didn't add the system namespace right ? if this is the case its an easy fix

**Comment by luizgserpa** [comment]
Yes! When the file is zipped happens this behavior

**Comment by Json2CSharp** [comment]
check again should be fixed

**Comment by luizgserpa** [comment]
Worked as expected! 
Thank you!

**Comment by Json2CSharp** [comment]
I will close this issue, if anything ill reopen, and thanks for letting me know
