### ISSUE TITLE
Add support for immutable C# classes

### ISSUE THREAD

**Issue by Jehoel** [Json2CSharp/Json2CSharpCodeGenerator#41]
* This is a requirement of a project of mine, and I'm working on an implementation in my fork right now.
* I'm creating this issue to refer from my PR, [as per the Contribution guidelines](https://github.com/Jehoel/Json2CSharpCodeGenerator/blob/master/README.md).
* The plan is to add a simple checkbox option that will effect these changes:
    *  Generated classes will have a Newtonsoft.Json-friendly constructor where each parameter is mapped to a property and each parameter has `[JsonProperty]`.
    *  Properties will be `{ get; }`-only, without setters.
    * List properties will be typed as `IReadOnlyList<T>` but the ctor parameter will be typed as `List<T>`.

**Comment by Json2CSharp** [comment]
Jehoel THANK YOU so much for your effort and contribution !! I will add an "Generate Immutable Classes " setting **tommorow** which will create the immutable class output. I will check to see if there's any conflict with other settings and just do a round of testing.

Is there a way I can buy you a cup of coffee for your hard work ??

**Comment by Jehoel** [comment]
Phew! I was far more concerned you'd reject my PR for scope-creep and for introducing _opinionated_ unrelated changes <_<

**Comment by Json2CSharp** [comment]
I had to reference the System.Data.Entity.Design.PluralizationServices cause for some reason my azure function (.Net Core 3.1) was throwing error with the System.Data.Entity.Design dll. not sure why

I had to also reference the newtonsoft dll cause It's throwing an error that It's not finding it.

Other than that I merged the changes and added a settings on the site. I will fix the download as zip files for this setting later (https://github.com/Json2CSharp/Json2CSharpCodeGenerator/issues/43)

Other than that thank you so much again for your contribution !!!

**Comment by Jehoel** [comment]
@Json2CSharp Oh, I didn't know the code runs in a .NET Core platform. I saw the main project was a .NET Framework 4.6.1 project so I can see why you might have problems with NuGet. You should change the main library project to target .NET Standard 2.0 then.

There are a load of pluralization libraries available on NuGet that are probably better than EF's - I just chose the first one that used EF's without needing to reference EF or have a local copy.

You shouldn't be getting any errors about Newtonsoft.Json - did you do a "NuGet Package Restore" when you loaded the solution in VS? What version of VS are you using?

**Comment by Json2CSharp** [comment]
Im using vs 2019, I'll an issue for changing to nuget packages hopefully it will work
