### ISSUE TITLE
Nullable for primitive types

### ISSUE THREAD

**Issue by elusive11** [Json2CSharp/Json2CSharpCodeGenerator#51]
It would be nice to be able to generate nullable field members for primitive types.  When serializing with JsonConvert, we can skip serializing field members that are null.

`public Nullable<int> StudentId;
`

**Comment by Json2CSharp** [comment]
ok so detect if a field can be nullable and infer the type to be nullable ? is that what u meant ?

**Comment by elusive11** [comment]
Basically I want to make use of the attribute NullValueHandling. If the value is null, it won't be serialized.  I can't set it to null if it's not nullable.

`        
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public Nullable<int> id;
`

In other cases, I need the field to be nullable to indicate it has no value.

**Comment by Json2CSharp** [comment]
NullValueHandling to ignore setting is done, as well as use nullable primitive types. However, support for automaticallly detect nullables is still not implemented but It's in the backlog
