### ISSUE TITLE
JsonPropertyName and immutable settings used together applies invalid attribute to ctor parameters

### ISSUE THREAD

**Issue by NeoXtreem** [Json2CSharp/Json2CSharpCodeGenerator#52]
The 'Use JsonPropertyName (.NET Core)' and 'Generate Immutable Classes' settings used together result in the `JsonPropertyName` attribute being applied to ctor parameters. This is invalid and results in compiler error [CS0592](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0592?f1url=%3FappId%3Droslyn%26k%3Dk(CS0592)).

**Comment by Json2CSharp** [comment]
Hey thanks for reaching out ! Can you please provide an example of this and the expected output ?

**Comment by Json2CSharp** [comment]
This is fixed yay
