### ISSUE TITLE
Idea: Support JSON comments

### ISSUE THREAD

**Issue by MartyIX** [Json2CSharp/Json2CSharpCodeGenerator#53]
Hi,

one thing that may (or may not) be useful is conversion of the following type:

```json
{
  "name": "Peter" // Person's name
}
```
(Yes, I know JSON comments are non-standard.)

This JSON would be translated into:

```csharp
public class Root
{
  /// <summary>Person's name</summary>
  public string name { get; set; }
}
```

I guess it's not that common thing to do but I'll leave it here for consideration.

Thanks!

**Comment by Json2CSharp** [comment]
Interesting but this is not JSON standard so not a lot of people use it like this, i have to close this unfortunately. but thanks for this suggestion

**Comment by MartyIX** [comment]
Yes, it's typically only found in API documentations on websites where they have JSON and add a comment like this because it's easy.

Thank you for reply! Keep up the good work.
