### ISSUE TITLE
.NET CORE 3+ system.text.json requires [JsonPropertyName("jsonField")]

### ISSUE THREAD

**Issue by ghhv** [Json2CSharp/Json2CSharpCodeGenerator#6]
As per the following references, 

- https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#use-a-custom-json-property-naming-policy
- https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization

The new CORE 3.x/5.x JSON de-serializer uses a different JsonProperty name to the NewtonSoft one.

Thanks very much!

**Comment by Json2CSharp** [comment]
Hey thanks a lot for mentioning this issue, will check it soon. I will probably will add a setting to support dot net core/ new json annotations.

**Comment by Json2CSharp** [comment]
This is done, a new option is made "Use JsonPropertyName (.NET Core)" , thanks again for the heads up, take care
