### ISSUE TITLE
Add option to generate record types from json

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Json2CSharp/Json2CSharpCodeGenerator#62]
C# 9 introduced record types, and they are a nice immutable way of representing data. In my projects I tend to use them to store json data, but the json to c# generator does not support them.

**Comment by Json2CSharp** [comment]
noted, thanks for the input, I will look into records as this is new to me

**Comment by HoLLy-HaCKeR** [comment]
Essentially, this json input:
```json
{
	"key": "my_key",
	"values": [
		{
			"id": 123,
			"real": true,
		},
		{
			"id": 456,
			"real": false
		}
	]
}
```

should turn into this C# code:
```cs
// Root myDeserializedClass = JsonSerializer.Deserialize<Root>(myJsonResponse);
public record Values(
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("real")] bool Real
);

public record Root(
    [property: JsonPropertyName("id")] string Key,
    [property: JsonPropertyName("values")] Values[] Values
);
```

I'm currently looking into adding support for this myself. I'll open a PR if I manage to get it done by today.
