### ISSUE TITLE
Missing: Donation button on the GitHub and the Website

### ISSUE THREAD

**Issue by EloiStree** [Json2CSharp/Json2CSharpCodeGenerator#65]
Guys your code is EPIC !!!
I don't want to disable AdsBlocker. But You made me win so many time , that I am willing to send a beer equivalent time to time.
Could you add a donation button to the website and/or GitHub ?

(I know that not a code issue, but you don't have obvious communication system around the website.)
![image](https://user-images.githubusercontent.com/20149493/134952320-9701a42c-dcc2-4362-90eb-b2a012b67029.png)

**Comment by Json2CSharp** [comment]
Awwwww thank you so much for this, made my day :D, I will look into this, maybe a paypal donate link would work
THANKS A LOT !

**Comment by Json2CSharp** [comment]
As much as I appreciate donations, I'm providing Azure developer course at discount rate. You can upgrade your knowledge !
