### ISSUE TITLE
Add Support for Immutable Records 

### ISSUE THREAD

**Issue by TonyValenti** [Json2CSharp/Json2CSharpCodeGenerator#66]
Would you please enhance the codegen so it will create classes like this:

```
public record RootJson {
  public ImmutableArray<DataJson> Data {get; init;} = ImmutableArray<DataJson>.Empty;

  public string Name {get; init;} = string.Empty;
  public string? Parent {get; init;}
}

public record DataJson {
  //... etc
}

```

**Comment by TonyValenti** [comment]
@Json2CSharp @Jehoel -
Can you merge the outstanding PRs?  If you do, I'd like to tackle this enhancement.

**Comment by Json2CSharp** [comment]
this is merged and there's now a setting to generate records instead of classes thanks to @HoLLy-HaCKeR

**Comment by TonyValenti** [comment]
@Json2CSharp - Can the WinForms app be updated to allow that?
