### ISSUE TITLE
JsonProperty NullValueHandling and Nullable Types 

### ISSUE THREAD

**Issue by yhackup** [Json2CSharp/Json2CSharpCodeGenerator#68]
Thank you for this beautiful site. Adding these features that I need to use very often will benefit many users.

I provide integration with all kinds of 3rd party APIs. It is not clear when it will come from 3rd party services.

1. [JsonProperty("agencyCode", **NullValueHandling = NullValueHandling.Ignore**)]
2. DateTime > DateTime? or Decimal > Decimal?  so they can be nullable

I believe it would be great if offered as an option

**Comment by Json2CSharp** [comment]
Im not sure if  I understand your requirements clearly, what exactly is the problem ?

**Comment by yhackup** [comment]
my english might be a little bad sorry
Let's draw
I want to have two options in settings, and this should work
![image](https://user-images.githubusercontent.com/15657038/145407733-5ef2c0fc-0546-40ce-b4db-f9129587d200.png)

**Comment by Json2CSharp** [comment]
oh yes nullable values option sounds good, I'm currently super busy with work so I anyone like to contribute to this feature that would be appreciated

**Comment by nealculiner** [comment]
+1 for nullable types, I just got burned by null exceptions. Great resource and much appreciated.

**Comment by Json2CSharp** [comment]
NullValueHandling to ignore setting is done, as well as use nullable primitive types. However, support for automaticallly detect nullables is still not implemented but It's in the backlog

**Comment by yhackup** [comment]
Thanks. god bless your hands.
