### ISSUE TITLE
Feature Request: Add a check box for making all the C# values strings.

### ISSUE THREAD

**Issue by 17SchallerJ** [Json2CSharp/Json2CSharpCodeGenerator#69]
Can you add an option to generate all C# object with all string values?
Or an option to make the default for unknown types string instead of object?

IE. if I have some json like this {"field1":0, "field2":null, "field3":"stringValue",...}
instead of generating: int field1, object field2, string field3...
could you make it generate: string field1, string field2, string field3...
or at the least generate: int field1, string field2, string field3...

Sorry if the title is bad, or if I explained things poorly. I don't usually make submissions to GitHub Projects.
I will try to remember to check back on this page in case you ask any questions, but I apologize if I forget.
Thanks!

**Comment by Json2CSharp** [comment]
yeah I agree with aloksharma, its better to have the types convert to strongly typed objects
