### ISSUE TITLE
Json2CSharp - is the source code available?

### ISSUE THREAD

**Issue by jchannon** [Json2CSharp/Json2CSharpCodeGenerator#7]
Hi I'm looking to do a F# version and was wondering if the C# version is available?

**Comment by Json2CSharp** [comment]
Hey thanks for reaching out Jonathan, i'm planning to make the source code available on github. it will be super easy to implement an interface and create new code writers but currently im super busy.

I will let you know all the details on how to contribute once i set up the documentation, settings, unit teste etc... 

Thanks and stay safe !

**Comment by Json2CSharp** [comment]
sauce is now available :)
