### ISSUE TITLE
Storing Address wrong.

### ISSUE THREAD

**Issue by whyn0thax** [Json2CSharp/Json2CSharpCodeGenerator#72]
Basically i was trying to Convert a json to C#, and i got a postcode, it should be a string and randomly got made into a int, that doesnt work due to Addresses or Postcodes always beeing Stored as a string.

Idk if its an error or wanted that way, it doesnt work like that tho.

Greetings

**Comment by Json2CSharp** [comment]
can you please post the json example so I can understand why it converted it to int

**Comment by Json2CSharp** [comment]
I will close this and if anything you can reopen the issue and provide the json example input and expected output
