### ISSUE TITLE
Json properties is not displaying after we select the checkbox

### ISSUE THREAD

**Issue by Santhosh88r** [Json2CSharp/Json2CSharpCodeGenerator#76]
Json properties is not displaying after we select the checkbox. Please fix

**Comment by Santhosh88r** [comment]
![Uploading Screenshot 2022-03-21 at 9.49.49 PM.png…]()

**Comment by Json2CSharp** [comment]
I can't open the screenshot
Can you please write your json input and the excepted output

**Comment by Json2CSharp** [comment]
I will close this as there was no response from the original author
