### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by rfphill** [Json2CSharp/Json2CSharpCodeGenerator#77]
This is likely not the place to report this but the option to convert XML to C classes returns a 500.  

This is, by far, the best xml to c# class site out there (due to being able to choose the option of changing the attribute/property names to different case formats).

**Comment by Json2CSharp** [comment]
oh my God thanks for letting me know, I had no idea it was down, must've been a faulty deployment. I can't thank you enough for letting me know. And thanks for the praises, Cheers and have a great day !
