### ISSUE TITLE
XML to C# issue

### ISSUE THREAD

**Issue by alexbk66** [Json2CSharp/Json2CSharpCodeGenerator#85]
I'm trying to convert the following XML, but it never finishes:

`<response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:noNamespaceSchemaLocation="http://www.aviationweather.gov/static/adds/schema/metar1_2.xsd">
<request_index>493837914</request_index>
<data_source name="metars"/>
<request type="retrieve"/>
<errors/>
<warnings/>
<time_taken_ms>3</time_taken_ms>
<data num_results="1">
<METAR>
<raw_text>KCMA 251355Z 00000KT 8SM CLR 16/14 A2995 RMK AO2 SLP149 T01610144</raw_text>
<station_id>KCMA</station_id>
<observation_time>2022-08-25T13:55:00Z</observation_time>
<latitude>34.22</latitude>
<longitude>-119.1</longitude>
<temp_c>16.1</temp_c>
<dewpoint_c>14.4</dewpoint_c>
<wind_dir_degrees>0</wind_dir_degrees>
<wind_speed_kt>0</wind_speed_kt>
<visibility_statute_mi>8.0</visibility_statute_mi>
<altim_in_hg>29.949802</altim_in_hg>
<sea_level_pressure_mb>1014.9</sea_level_pressure_mb>
<quality_control_flags>
<auto_station>TRUE</auto_station>
</quality_control_flags>
<sky_condition sky_cover="CLR"/>
<flight_category>VFR</flight_category>
<metar_type>METAR</metar_type>
<elevation_m>20.0</elevation_m>
</METAR>
</data>
</response>`

**Comment by Json2CSharp** [comment]
no idea why its happening It's passing the test in the source code, give me some time to check, but thanks for letting me know !!!

**Comment by profkaygee** [comment]
This is still an issue. I am assuming you are still working on it.

**Comment by salvesen** [comment]
I am also facing issues when trying to convert XML to C#, on multiple browsers. its really all XML text, but this is the latest i tried:

`<?xml version="1.0"?>
<response>
  <params>
    <bins>
      <bin>
        <bin_id>12004</bin_id>
        <content>21</content>
        <target_grid>1</target_grid>
      </bin>
    </bins>
  </params>
</response>`

**Comment by Json2CSharp** [comment]
It should work now, thanks everyone for letting me know

**Comment by HHK01** [comment]
just testing email notification
