### ISSUE TITLE
WAP

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [Json2CSharp/Json2CSharpCodeGenerator#86]
https://json2csharp.com/ has an ad on the top that says #WAP. I assume this meant "with a passion" at the time it was written, but this acronymn has taken on new meaning thanks to Cardi B and Megan Thee Stallion, particularly if used alongside the phrase "Certified freak 7 days a week".

![image](https://user-images.githubusercontent.com/14170257/189229987-9740f1e0-7966-41f7-8e57-2f6aef951fa6.png)

Just thought you might want to be aware.

**Comment by Json2CSharp** [comment]
this is fixed thanks for letting me know Jesse. Cheers
